import type { Metadata } from "next";
import localFont from 'next/font/local'
import "./globals.css";

const makenFont = localFont({
  // 'src' folder ke bahar 'public' tak pohnchnay ke liye
  src: '../../public/fonts/Maken.otf', 
  variable: '--font-maken',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${makenFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
